---
title: "CodeBook for 'Getting and Cleaning Data' Project Course"
author: "Bastien MAROT"
date: "24 mai 2015"
output: html_document
---

## Introduction

This codebook gives a quick description of the 'step5data.csv' file generated by my 'run_analysis.R' script.
The file contains **180 lines** and **81 columns**.

## Lines

The 180 lines stand for the (30 subjects x 6 activities) sets of measures

## Columns

The 81 columns are :

- col1  'Subj'  int     integer identifying the subject, from 1 to 30  
- col2  'Act'   Factor  name of the activity
- col 3 to col 81  ==> the average of each of the 79 'mean' and 'std' variables, for each Subject and each Activity

Those 79 'mean' and 'std' variables are the following :

- col3  tBodyAcc-mean()-X
- col4	tBodyAcc-mean()-Y
- col5	tBodyAcc-mean()-Z
- col6	tGravityAcc-mean()-X
- col7	tGravityAcc-mean()-Y
- col8	tGravityAcc-mean()-Z
- col9	tBodyAccJerk-mean()-X
- col10	tBodyAccJerk-mean()-Y
- col11	tBodyAccJerk-mean()-Z
- col12	tBodyGyro-mean()-X
- col13	tBodyGyro-mean()-Y
- col14	tBodyGyro-mean()-Z
- col15	tBodyGyroJerk-mean()-X
- col16	tBodyGyroJerk-mean()-Y
- col17	tBodyGyroJerk-mean()-Z
- col18	tBodyAccMag-mean()
- col19	tGravityAccMag-mean()
- col20	tBodyAccJerkMag-mean()
- col21	tBodyGyroMag-mean()
- col22	tBodyGyroJerkMag-mean()
- col23	fBodyAcc-mean()-X
- col24	fBodyAcc-mean()-Y
- col25	fBodyAcc-mean()-Z
- col26	fBodyAcc-meanFreq()-X
- col27	fBodyAcc-meanFreq()-Y
- col28	fBodyAcc-meanFreq()-Z
- col29	fBodyAccJerk-mean()-X
- col30	fBodyAccJerk-mean()-Y
- col31	fBodyAccJerk-mean()-Z
- col32	fBodyAccJerk-meanFreq()-X
- col33	fBodyAccJerk-meanFreq()-Y
- col34	fBodyAccJerk-meanFreq()-Z
- col35	fBodyGyro-mean()-X
- col36	fBodyGyro-mean()-Y
- col37	fBodyGyro-mean()-Z
- col38	fBodyGyro-meanFreq()-X
- col39	fBodyGyro-meanFreq()-Y
- col40	fBodyGyro-meanFreq()-Z
- col41	fBodyAccMag-mean()
- col42	fBodyAccMag-meanFreq()
- col43	fBodyBodyAccJerkMag-mean()
- col44	fBodyBodyAccJerkMag-meanFreq()
- col45	fBodyBodyGyroMag-mean()
- col46	fBodyBodyGyroMag-meanFreq()
- col47	fBodyBodyGyroJerkMag-mean()
- col48	fBodyBodyGyroJerkMag-meanFreq()
- col49	tBodyAcc-std()-X
- col50	tBodyAcc-std()-Y
- col51	tBodyAcc-std()-Z
- col52	tGravityAcc-std()-X
- col53	tGravityAcc-std()-Y
- col54	tGravityAcc-std()-Z
- col55	tBodyAccJerk-std()-X
- col56	tBodyAccJerk-std()-Y
- col57	tBodyAccJerk-std()-Z
- col58	tBodyGyro-std()-X
- col59	tBodyGyro-std()-Y
- col60	tBodyGyro-std()-Z
- col61	tBodyGyroJerk-std()-X
- col62	tBodyGyroJerk-std()-Y
- col63	tBodyGyroJerk-std()-Z
- col64	tBodyAccMag-std()
- col65	tGravityAccMag-std()
- col66	tBodyAccJerkMag-std()
- col67	tBodyGyroMag-std()
- col68	tBodyGyroJerkMag-std()
- col69	fBodyAcc-std()-X
- col70	fBodyAcc-std()-Y
- col71	fBodyAcc-std()-Z
- col72	fBodyAccJerk-std()-X
- col73	fBodyAccJerk-std()-Y
- col74	fBodyAccJerk-std()-Z
- col75	fBodyGyro-std()-X
- col76	fBodyGyro-std()-Y
- col77	fBodyGyro-std()-Z
- col78	fBodyAccMag-std()
- col79	fBodyBodyAccJerkMag-std()
- col80	fBodyBodyGyroMag-std()
- col81	fBodyBodyGyroJerkMag-std()

